### ISSUE TITLE
Deinstalled packages

### ISSUE THREAD

**Issue by lassiewoof** [Utappia/uCareSystem#1]
In my opinion it could be useful to add a command to clean packages in deinstall state.
You can do it simply adding this line of code:

`dpkg --get-selections | grep deinstall | cut -f1 | xargs dpkg --purge`

**Comment by cerebrux** [comment]
Nice one I will check it

**Comment by cerebrux** [comment]
adding contex that needs to be tested https://askubuntu.com/questions/687295/how-to-purge-previously-only-removed-packages
