### ISSUE TITLE
implement pkexec instead of gksu

### ISSUE THREAD

**Issue by cerebrux** [Utappia/uCareSystem#17]
gksu, gksudo, kdesu are good. Instead pkexec should be preferred

**Comment by kq01526** [comment]
> @cerebrux wrote:
> gksu, gksudo, kdesu are good. Instead pkexec should be preferred

Why?

**Comment by cerebrux** [comment]
@kq01526 you can read more on the matter here https://askubuntu.com/questions/78352/when-to-use-pkexec-vs-gksu-gksudo

Let me just add, that because gksu/gksudo/kdesu is Desktop environment dependent, pkexec doesn't care what Desktop Env. you use. So technically, it's more modern (according to the freedesktop protocols) and more convenient ;)
