### ISSUE TITLE
Packages that need to be installed on Debian 9

### ISSUE THREAD

**Issue by unquietwiki** [Utappia/uCareSystem#21]
I think the following command should deal with the missing dependencies

**apt install dirmngr policykit-1 gnupg2 deborphan xterm -y**

**Comment by unquietwiki** [comment]
On Ubuntu...

**apt install dirmngr policykit-1 gnupg2 deborphan xterm software-properties-common -y**

**Comment by cerebrux** [comment]
Thanks for the report.

**Comment by karlegas** [comment]
The following packages have unmet dependencies:  This is in Ubuntu Server 16.04
 ucaresystem-core : Depends: deborphan but it is not installed
                    Depends: xterm
E: Unmet dependencies. Try using -f.


sudo apt-get -f install
Reading package lists...
Building dependency tree...
Reading state information...
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  linux-image-4.4.0-157-generic linux-modules-4.4.0-157-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  deborphan dialog xbitmaps xterm
Suggested packages:
  xfonts-cyrillic
The following NEW packages will be installed:
  deborphan dialog xbitmaps xterm
0 upgraded, 4 newly installed, 0 to remove and 11 not upgraded.
1 not fully installed or removed.
Need to get 943 kB of archives.
After this operation, 3,627 kB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.

I cannot select Y/N only abor byself

**Comment by cerebrux** [comment]
fixed in 
3ad83aa
