### ISSUE TITLE
ucaresystem-core requires policykit-1

### ISSUE THREAD

**Issue by ewomack** [Utappia/uCareSystem#25]
When using ubuntu-minimal from a clean install and adding the PPA for Utappia, ucaresystem-core will not run as it needs policykit-1 to start. It is not loaded during dependency phase of the ucaresystem-core install and is not included in ubuntu-minimal. Simple fix is:

`sudo apt install policykit-1`

Adding policykit-1 to the dependency of the package will permanently fix this.

**Comment by cerebrux** [comment]
fixed in 
3ad83aa
