### ISSUE TITLE
party installed on parrotsec

### ISSUE THREAD

**Issue by jemadux** [Utappia/uCareSystem#26]
Checking if Utappia Repository exists in your system

Adding Utappia repository
/var/lib/dpkg/info/ucaresystem-core.postinst: 34: /var/lib/dpkg/info/ucaresystem-core.postinst: add-apt-repository: not found
dpkg: error processing package ucaresystem-core (--configure):
 installed ucaresystem-core package post-installation script subprocess returned error exit status 127
Προέκυψαν σφάλματα κατά την επεξεργασία του:
 ucaresystem-core
Configuring sandbox profiles....
Sandbox profiles updated!
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by cerebrux** [comment]
Ευχαριστώ θα το δω !

**Comment by cerebrux** [comment]
fixed in 3ad83aa
