### ISSUE TITLE
WSL2: Error getting authority: Error initializing authority: Could not connect: No such file or directory

### ISSUE THREAD

**Issue by ferdavs** [Utappia/uCareSystem#30]
Currently gives error
```
Error getting authority: Error initializing authority: Could not connect: No such file or directory
```

**Comment by cerebrux** [comment]
Thanks for the report. 

A workaround until I fix it is to just change the first line in the script (`/usr/bin/ucaresystem-core`) with your favorite text editor.


```
#!/usr/bin/pkexec /bin/bash
```
to :
```
#!/bin/bash
```
and then you can run it with:

```
sudo ucaresystem-core
```

**Comment by clayauld** [comment]
I have added some general support in my fork. @cerebrux, any interest in getting maintainer help to support bug fixes and PRs? I use this code and would be willing to contribute. I can open a PR if that's easiest for you.

**Comment by cerebrux** [comment]
fixed in https://github.com/Utappia/uCareSystem/releases/tag/v24.10.07
