### ISSUE TITLE
υποστηρίξη για το nala 

### ISSUE THREAD

**Issue by jemadux** [Utappia/uCareSystem#33]
ναι το apt ειναι πολύ καλο εργαλείο αλλά στην αντιλήψη μου ήρθε και το[ nala](https://github.com/volitank/nala)
νομίζω  θα είναι μια καλή ιδέα να το αξιοποιούμε .

**Comment by cerebrux** [comment]
καλή ιδέα, αλλά επειδή το uCareSystem χρησιμοποιείται απο διάφορες Debian διανομές και σε διαφορετικές συνθήκες, η αλλαγή απο "apt" που ειναι built in σε κάτι εξωτερικό, κάποιου 3ου κατασκευαστή είναι ακραία αλλαγή.

Οπότε δεν μπορεί να υλοποιηθεί κάτι τέτοιο
