### ISSUE TITLE
Error getting authority

### ISSUE THREAD

**Issue by WildeWebMarketing** [Utappia/uCareSystem#34]
I've never had any issues until now, hopefully someone can help me fix this.

When I try to run 'sudo ucaresystem-core', it throws the following error:

'Error getting authority: Error initializing authority: Could not connect: No such file or directory'

This issue just came out of nowhere, I haven't made any changes myself, other than regular updates using uCareSystem.

**Comment by cerebrux** [comment]
Can you please add some info on what distribution and version you had the issue ?

**Comment by cerebrux** [comment]
Dorman't and no feedback. Closing for the moment
