### ISSUE TITLE
UCareSystem-Core Not Getting All Updates Sept 17, 2023

### ISSUE THREAD

**Issue by JeffRedd** [Utappia/uCareSystem#35]
I love this little program. I just found out about it about 3 months ago and it’s been terrific, however lately there has been some problems with the updates.  It seems that I haven’t been getting some of my updates, particularly GNOME updates in Kubuntu 22.04.3 LTS.  I have another computer with Kubuntu 22.04.3 LTS and it is doing the same thing and another computer with Lubuntu 22.04.2 LTS and it doesn’t get all the updates either. This may be something new.  Maybe it’s just confined to the Ubuntu “flavors”? I’m not sure.  Thanks

**Comment by cerebrux** [comment]
You have to show me some outputs in your terminal or else I won't be able to pin point your particular issue. 
Can you run it and give me some outputs ?

**Comment by JeffRedd** [comment]
Cerebrux,  Here is the list of item it claims it missed: 

“Flatsweep Update to version v2023.9.18 (stable)
Breeze GTK theme Update to version 5.27.6 (3.22)
Freedesktop Platform Update to version 22.08.15 (22.08)
GNOME Application Platform version 3.38
Update to version 44
Mesa Update to version 23.1.6 (22.08-extra)
Mesa Update to version 23.1.6 (22.08)
io.github.giantpinkrobots.flatsweep.Locale
Update to version stable
org.freedesktop.Platform.Locale Update to version 22.08
org.freedesktop.Platform.VAAPI.Intel Update to version 22.08
org.gnome.Platform.Locale Update to version 44”

As it is right now, it is working fine. Maybe it was a glitch or something that had to do with bad updates? It happened about a month ago but I’m not getting screen errors right now.
   
I do know that not all the updates goes through and some of them still have to be done through the “Discovery Software Center” Updates tab. I don’t have any complaints about that and it doesn’t always happen but I wanted to let you know what is not getting updated after running the “sudo ucaresystem-core” updates.   I’m running Kubuntu 22.04.3 LTS x86_64 with Plasma 5.24.7.

Overall I really love this program and it also includes includes all the service packages for Ubuntu Pro which is a huge advantage.  I just sent you a small donation €30 to tell you how much I appreciate this program.

**Comment by cerebrux** [comment]
> “Flatsweep Update to version v2023.9.18 (stable) Breeze GTK theme Update to version 5.27.6 (3.22) Freedesktop Platform Update to version 22.08.15 (22.08) GNOME Application Platform version 3.38 Update to version 44 Mesa Update to version 23.1.6 (22.08-extra) Mesa Update to version 23.1.6 (22.08) io.github.giantpinkrobots.flatsweep.Locale Update to version stable org.freedesktop.Platform.Locale Update to version 22.08 org.freedesktop.Platform.VAAPI.Intel Update to version 22.08 org.gnome.Platform.Locale Update to version 44”

Without being 100% sure, I asume that these packages are probably flatpacks (?). Or, most probable situation they are marked as "kept back" for a wile until some of their dependencies are also up to date  
 
> As it is right now, it is working fine. Maybe it was a glitch or something that had to do with bad updates? It happened about a month ago but I’m not getting screen errors right now.

Nice. I will be keeping an eye on the situation as I usually run ucaresystem followed by a shutdown and leave my computer alone and never look at the outputs. 
So I will be keeping this issue open for the time being. 

> Overall I really love this program and it also includes includes all the service packages for Ubuntu Pro which is a huge advantage. I just sent you a small donation €30 to tell you how much I appreciate this program.

I am so happy that it is useful for you ! Thank you so much for your support !
