### ISSUE TITLE
No internet connection detected in VMs

### ISSUE THREAD

**Issue by cerebrux** [Utappia/uCareSystem#54]
If you use uCareSystem in a VM with minimal server installation, there is a chance that uCareSystem will report a false positive indication of NO internet connection.

This is due to the m,issing package "ping" form the minimal system

**Comment by CharalamposKarampasis** [comment]
Hi all, yesterday after update's ucare system the issue of no internet connection remains. 
![Screenshot from 2024-07-16 15-52-35](https://github.com/user-attachments/assets/36ca12c1-fa40-421b-a68c-b1f68fd7e24e)
![Screenshot from 2024-07-16 15-55-17](https://github.com/user-attachments/assets/ea8ba710-2c03-4e0e-a117-ffdfeb1db060)
See attached two sreenshots.

**Comment by cerebrux** [comment]
Oh I see now ! The curl package is missing from your system.

For the meantime you can install it :

sudo apt install curl 

This will fix the issue until I upload a fix. Please comment back again if this fixed it for you or it is still a problem

**Comment by CharalamposKarampasis** [comment]
Hi Salih


Issue fixed!! Thank you for the support.

Regards

Charalampos
