### ISSUE TITLE
uCareSystem 24.06 version  in Linux Lite 6.6 haw stopped working 

### ISSUE THREAD

**Issue by cerebrux** [Utappia/uCareSystem#63]
Moved comment https://github.com/Utappia/uCareSystem/commit/c766c3f062ada04666e3327b9df3bd534d89ba2d#commitcomment-144437077 here:

OK, I reinstalled the program and started it. It doesn't work. (see Screen1.jpg and Screen2.jpg). Calling it in the terminal didn't work either (see Screen3.jpg). The attempt to start the program as a script (previously copied from /bin/usr/ to /home/bbr/Desktop) was also unsuccessful (see Screen4.jpg).
![Screen4](https://github.com/user-attachments/assets/3a9b5e18-5937-4277-9bd4-be65bc836259)
![Screen3](https://github.com/user-attachments/assets/5d040c3b-90da-4b2d-9f14-021c9600a152)
![Screen2](https://github.com/user-attachments/assets/38dfb697-7fc2-4e3e-a367-e0c2548d8cca)
![Screen1](https://github.com/user-attachments/assets/16798db6-91b6-4291-ac09-b6c536e9766c)

Sorry, the order is from bottom to top. screenshot 1 is at the bottom, screenshot 4 is at the top.

**Comment by cerebrux** [comment]
@Benno726 please run the following command to do a workaround until I push a fix for your problem:

```
sed -i 's/^set -e/#set -e/' /usr/bin/ucaresystem-core
``` 
This will comment out the `set -e` in the program so that it doesn't exit prematurely.

**Comment by Benno726** [comment]
Thank you very much. It works if I enter the command as superuser 

sudo sed -i 's/^set -e/#set -e/' /usr/bin/ucaresystem-core

**Comment by cerebrux** [comment]
Thanks @Benno726 for helping me to pin point the Issue. I have good news ! I am currently testing a fix on Linux Lite 6.6 and Linux Lite 7.0. Hopefully within this week I will push an update that will permanently fix your issue.
