### ISSUE TITLE
Unresolved ucaresystem-core depends on pkexec;

### ISSUE THREAD

**Issue by gchr** [Utappia/uCareSystem#67]
Installing into a fresh Ubuntu 20.04.4 with: `sudo dpkg -i ucaresystem-core_24.07.28_all.deb`
 and subsequent `sudo apt-get -f install` to fix dependencies,
in the end I'm stuck at this:
```
$ sudo dpkg -i ucaresystem-core_24.07.28_all.deb 
(Reading database ... 157094 files and directories currently installed.)
Preparing to unpack ucaresystem-core_24.07.28_all.deb ...
Unpacking ucaresystem-core (24.07.28) over (24.07.28) ...
dpkg: dependency problems prevent configuration of ucaresystem-core:
 ucaresystem-core depends on pkexec; however:
  Package pkexec is not installed.

dpkg: error processing package ucaresystem-core (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 ucaresystem-core
```

However pkexec is actually installed:
```
$ pkexec --version
pkexec version 0.105
```

**Comment by cerebrux** [comment]
Thanks for taking the time for reporting. I confirm that there is a bug and I will push a fix ASAP

**Comment by cerebrux** [comment]
> Installing into a fresh Ubuntu 20.04.4 with: `sudo dpkg -i ucaresystem-core_24.07.28_all.deb` and subsequent `sudo apt-get -f install` to fix dependencies, in the end I'm stuck at this:

By the way, not related to your issue but the proper way of installing `.deb` packages is using `apt`. eg:

```
sudo apt install ./ucaresystem-core_24.07.28_all.deb
```

**Comment by cerebrux** [comment]
fix released, please update

**Comment by gchr** [comment]
Fix is OK!
Thank you!
