### ISSUE TITLE
"Stop the countdown" may lead to confusion

### ISSUE THREAD

**Issue by cerebrux** [Utappia/uCareSystem#81]
When the user reads "stop the countdown" may think that it skips the countdown when it actually STOPS the procedure and exits uCareSystem

https://github.com/Utappia/uCareSystem/blob/1243e83e89c06c4affaf1b231322559cb8de05ff/ucaresystem-core#L63

**Comment by billniakas** [comment]
Don't fix it I like it just the way it is
